ui=fluidPage(titlePanel("Карта абитуриентов"),
             fluidRow(
               sidebarPanel(width = 2, 
                            radioButtons('format', 'Document format', c('PDF', 'HTML', 'Word'),
                                         inline = TRUE),
                            downloadButton('downloadReport'),
                            p("Для карты"),
                            selectInput("god", "Год",
                                        choices=colnames(imapt)),
                            p("Для графиков: 1, 6"),
                            selectInput(
                              "gorod1", "Поступали",
                              choices=c("По УдГУ"="Поступали_По_УдГУ","Ижевск"="Поступали_Ижевск", 
                                        "Сарапул"="Поступали_Сарапул", "Воткинкс"="Поступали_Воткинкс",
                                        "Можга"="Поступали_Можга", "Глазов"="Поступали_Глазов", 
                                        "Камбарка"="Поступали_Камбарка",
                                        "Районы Удмуртии"="Поступали_Районы_Удмуртии", 
                                        "Остальное"="Поступали_Остальное")),
                            p("Для графиков: 2, 6"),
                            selectInput("gorod2", "Поступили",
                                        choices=c("По УдГУ"="Поступили_По_УдГУ","Ижевск"="Поступили_Ижевск", 
                                                  "Сарапул"="Поступили_Сарапул", "Воткинкс"="Поступили_Воткинкс",
                                                  "Можга"="Поступили_Можга", "Глазов"="Поступили_Глазов", 
                                                  "Камбарка"="Поступили_Камбарка",
                                                  "Районы Удмуртии"="Поступили_Районы_Удмуртии", 
                                                  "Остальное"="Поступили_Остальное")), 
                            p("Для графиков: 3, 9"),
                            selectInput("god1", "Год",
                                        choices=colnames(izh.T)),
                            p("Для графиков: 5"),
                            selectInput("god2", "Год",
                                        choices=colnames(iz)),
                            p("Для графиков: 4, 10"),
                            selectInput("god3", "Год",
                                        choices=colnames(izh1.T)),
                            p("Для графиков: 12"),
                            selectInput("gorod3", "Город",
                                        choices=colnames(nm[,-1])),
                            p("Для графиков: 12"),
                            selectInput("gorod4", "Город",
                                        choices=colnames(izhy[,-1])),
                            p("Для графиков: 13-22"),
                            selectInput("inst", "Факультет",
                                        choices=colnames(izhevsk1[,-1]))),
               mainPanel(width = 10, 
                         plotOutput("plot1"),plotOutput("plot2"),
                         plotOutput("plot3"), plotOutput("plot31"), plotOutput("plot4"), 
                         plotOutput("matplot", click = "plot_click"), verbatimTextOutput("info"),
                         plotOutput("matplot1", click = "plot_click1"), verbatimTextOutput("info1"), 
                         plotOutput("matplot2", click = "plot_click2"), verbatimTextOutput("info2"),
                         plotOutput("pie"), plotOutput("pie1"),plotOutput("plot45"),
                         plotOutput("matplot3", click = "plot_click3"), verbatimTextOutput("info3"),
                         plotOutput("matplot4", click = "plot_click4"), verbatimTextOutput("info4"),
                         plotOutput("matplot5", click = "plot_click5"), verbatimTextOutput("info5"),
                         plotOutput("matplot6", click = "plot_click6"), verbatimTextOutput("info6"),
                         plotOutput("matplot7", click = "plot_click7"), verbatimTextOutput("info7"),
                         plotOutput("matplot8", click = "plot_click8"), verbatimTextOutput("info8"),
                         plotOutput("matplot9", click = "plot_click9"), verbatimTextOutput("info9"),
                         plotOutput("matplot10", click = "plot_click10"), verbatimTextOutput("info10"),
                         plotOutput("matplot11", click = "plot_click11"), verbatimTextOutput("info11"),
                         plotOutput("matplot12", click = "plot_click12"), verbatimTextOutput("info12"),
                         plotOutput("matplot13", click = "plot_click13"), verbatimTextOutput("info13"))))